version: "3.9"

services:
  mcp-service:
    build: .
    container_name: mcp_container
    ports:
      - "8081:8080"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
